version: '3.8'

services:
  microservicio-pedidos:
    build:
      context: .
      dockerfile: MicroservicioDePedidos/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - rabbitmq

  microservicio-inventario:
    build:
      context: .
      dockerfile: InventarioService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tucontraseña
      POSTGRES_DB: sistema_pedidos
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
